import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { DependencyGraph, ResolvedPackage, RootPackageJson } from "../src/lockfile/types";
import { npmGenerator, npmParser } from "../src/lockfile/npm";
import { yarnGenerator, yarnParser } from "../src/lockfile/yarn";
import { pnpmGenerator, pnpmParser } from "../src/lockfile/pnpm";
import { bunGenerator, bunParser } from "../src/lockfile/bun";

// ── Test fixtures ──────────────────────────────────────────────────

function createTestGraph(): DependencyGraph {
  const graph: DependencyGraph = new Map();

  graph.set("node_modules/express", {
    name: "express",
    version: "4.21.0",
    resolved: "https://registry.npmjs.org/express/-/express-4.21.0.tgz",
    integrity: "sha512-VqcNGcj/Id5ZT1LZ/cfihi3ttTn+NJmkli2eZAGUUYBhQ==",
    dev: false,
    dependencies: { accepts: "~1.3.8", "body-parser": "1.20.3" },
    engines: { node: ">= 0.10.0" },
  });

  graph.set("node_modules/accepts", {
    name: "accepts",
    version: "1.3.8",
    resolved: "https://registry.npmjs.org/accepts/-/accepts-1.3.8.tgz",
    integrity: "sha512-PYAthTa2m2VKxuvSD3DPC/Gy+U+sOA1LAuT8mkmRuvw==",
    dev: false,
    dependencies: { "mime-types": "~2.1.34", negotiator: "0.6.3" },
  });

  graph.set("node_modules/typescript", {
    name: "typescript",
    version: "5.4.5",
    resolved: "https://registry.npmjs.org/typescript/-/typescript-5.4.5.tgz",
    integrity: "sha512-vcI4UpRgg81oIRUFwR0WSIHKt11nJ7SAVlQ==",
    dev: true,
    bin: { tsc: "bin/tsc", tsserver: "bin/tsserver" },
    engines: { node: ">=14.17" },
  });

  return graph;
}

function createTestRootPkg(): RootPackageJson {
  return {
    name: "test-project",
    version: "1.0.0",
    dependencies: { express: "4.21.0" },
    devDependencies: { typescript: "5.4.5" },
  };
}

// ── npm ────────────────────────────────────────────────────────────

describe("npm lock file", () => {
  it("generates valid package-lock.json", () => {
    const graph = createTestGraph();
    const rootPkg = createTestRootPkg();

    const output = npmGenerator.generate(graph, rootPkg);
    const parsed = JSON.parse(output);

    assert.equal(parsed.lockfileVersion, 3);
    assert.equal(parsed.requires, true);
    assert.ok(parsed.packages[""]);
    assert.equal(parsed.packages[""].name, "test-project");
    assert.equal(parsed.packages["node_modules/express"].version, "4.21.0");
    assert.equal(parsed.packages["node_modules/typescript"].dev, true);
    assert.equal(parsed.packages["node_modules/accepts"].version, "1.3.8");
  });

  it("round-trips through parser", () => {
    const graph = createTestGraph();
    const rootPkg = createTestRootPkg();

    const output = npmGenerator.generate(graph, rootPkg);
    const reparsed = npmParser.parse(output);

    assert.equal(reparsed.size, 3);
    assert.equal(reparsed.get("node_modules/express")?.version, "4.21.0");
    assert.equal(reparsed.get("node_modules/typescript")?.dev, true);
    assert.equal(reparsed.get("node_modules/accepts")?.version, "1.3.8");
  });

  it("includes resolved URLs and integrity hashes", () => {
    const graph = createTestGraph();
    const output = npmGenerator.generate(graph, createTestRootPkg());
    const parsed = JSON.parse(output);

    const expr = parsed.packages["node_modules/express"];
    assert.ok(expr.resolved?.includes("registry.npmjs.org"));
    assert.ok(expr.integrity?.startsWith("sha512-"));
  });

  it("sorts packages deterministically", () => {
    const graph = createTestGraph();
    const output = npmGenerator.generate(graph, createTestRootPkg());
    const parsed = JSON.parse(output);

    const keys = Object.keys(parsed.packages).filter((k) => k !== "");
    const sorted = [...keys].sort();
    assert.deepEqual(keys, sorted);
  });
});

// ── yarn ───────────────────────────────────────────────────────────

describe("yarn lock file", () => {
  it("generates yarn.lock with header", () => {
    const graph = createTestGraph();
    const output = yarnGenerator.generate(graph, createTestRootPkg());

    assert.ok(output.startsWith("# THIS IS AN AUTOGENERATED FILE"));
    assert.ok(output.includes("# yarn lockfile v1"));
  });

  it("generates entries with version, resolved, integrity", () => {
    const graph = createTestGraph();
    const output = yarnGenerator.generate(graph, createTestRootPkg());

    assert.ok(output.includes('version "4.21.0"'));
    assert.ok(output.includes("resolved \"https://registry.npmjs.org/express/"));
    assert.ok(output.includes("integrity sha512-"));
  });

  it("includes dependencies sub-section", () => {
    const graph = createTestGraph();
    const output = yarnGenerator.generate(graph, createTestRootPkg());

    assert.ok(output.includes("dependencies:"));
    assert.ok(output.includes('accepts "~1.3.8"'));
  });

  it("round-trips through parser", () => {
    const graph = createTestGraph();
    const rootPkg = createTestRootPkg();

    const output = yarnGenerator.generate(graph, rootPkg);
    const reparsed = yarnParser.parse(output);

    assert.ok(reparsed.has("node_modules/express"));
    assert.equal(reparsed.get("node_modules/express")?.version, "4.21.0");
    assert.ok(reparsed.has("node_modules/accepts"));
    assert.ok(reparsed.has("node_modules/typescript"));
  });
});

// ── pnpm ───────────────────────────────────────────────────────────

describe("pnpm lock file", () => {
  it("generates pnpm-lock.yaml with header", () => {
    const graph = createTestGraph();
    const output = pnpmGenerator.generate(graph, createTestRootPkg());

    assert.ok(output.includes("lockfileVersion: '9.0'"));
    assert.ok(output.includes("importers:"));
    assert.ok(output.includes("packages:"));
  });

  it("includes importers section with root dependencies", () => {
    const graph = createTestGraph();
    const output = pnpmGenerator.generate(graph, createTestRootPkg());

    assert.ok(output.includes("dependencies:"));
    assert.ok(output.includes("express:"));
    assert.ok(output.includes("specifier: 4.21.0"));
    assert.ok(output.includes("devDependencies:"));
    assert.ok(output.includes("typescript:"));
  });

  it("includes package entries with resolution", () => {
    const graph = createTestGraph();
    const output = pnpmGenerator.generate(graph, createTestRootPkg());

    assert.ok(output.includes("'express@4.21.0':"));
    assert.ok(output.includes("resolution: {integrity: sha512-"));
  });

  it("marks dev packages", () => {
    const graph = createTestGraph();
    const output = pnpmGenerator.generate(graph, createTestRootPkg());

    // typescript should have dev: true
    const tsSection = output.substring(output.indexOf("'typescript@5.4.5':"));
    assert.ok(tsSection.includes("dev: true"));
  });

  it("round-trips through parser", () => {
    const graph = createTestGraph();
    const rootPkg = createTestRootPkg();

    const output = pnpmGenerator.generate(graph, rootPkg);
    const reparsed = pnpmParser.parse(output);

    assert.ok(reparsed.has("node_modules/express"));
    assert.equal(reparsed.get("node_modules/express")?.version, "4.21.0");
    assert.ok(reparsed.has("node_modules/typescript"));
    assert.equal(reparsed.get("node_modules/typescript")?.dev, true);
  });
});

// ── bun ────────────────────────────────────────────────────────────

describe("bun lock file", () => {
  it("generates valid JSON", () => {
    const graph = createTestGraph();
    const output = bunGenerator.generate(graph, createTestRootPkg());

    const parsed = JSON.parse(output);
    assert.equal(parsed.lockfileVersion, 0);
    assert.ok(parsed.workspaces);
    assert.ok(parsed.packages);
  });

  it("includes root workspace", () => {
    const graph = createTestGraph();
    const output = bunGenerator.generate(graph, createTestRootPkg());
    const parsed = JSON.parse(output);

    const root = parsed.workspaces[""];
    assert.equal(root.name, "test-project");
    assert.deepEqual(root.dependencies, { express: "4.21.0" });
    assert.deepEqual(root.devDependencies, { typescript: "5.4.5" });
  });

  it("includes packages as tuples", () => {
    const graph = createTestGraph();
    const output = bunGenerator.generate(graph, createTestRootPkg());
    const parsed = JSON.parse(output);

    assert.ok(Array.isArray(parsed.packages.express));
    assert.equal(parsed.packages.express[0], "express@4.21.0");
  });

  it("round-trips through parser", () => {
    const graph = createTestGraph();
    const rootPkg = createTestRootPkg();

    const output = bunGenerator.generate(graph, rootPkg);
    const reparsed = bunParser.parse(output);

    assert.ok(reparsed.has("node_modules/express"));
    assert.equal(reparsed.get("node_modules/express")?.version, "4.21.0");
    assert.ok(reparsed.has("node_modules/typescript"));
  });
});
